[package]
name = "html-template-scraper"
version = "0.1.0"
edition = "2021"
authors = ["Dilshad <a-rustacean@outlook.com>"]

[dependencies]
futures = "0.3.28"
lazy_static = "1.4.0"
regex = "1.8.4"
reqwest = "0.11.23"
scraper = "0.18.1"
tokio = { version = "1.29.1", features = ["rt", "macros", "rt-multi-thread"] }
url = "2.5.0"
xmlwriter = "0.1.0"
