[package]
name = "html-template-scraper"
version = "0.1.0"
edition = "2021"
authors = ["Dilshad <a-rustacean@outlook.com>"]

[dependencies]
futures = "0.3.30"
lazy_static = "1.5.0"
regex = "1.10.5"
reqwest = "0.12.5"
scraper = "0.19.0"
tokio = { version = "1.38.1", features = ["rt", "macros", "rt-multi-thread"] }
url = "2.5.2"
xmlwriter = "0.1.0"
