name: Compile

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Compile to all targets
        run: |
          # Set the project name
          project_name="html-template-scraper"
          cargo build --release --target x86_64-unknown-linux-gnu
          mkdir artifacts

          cp target/x86_64-unknown-linux-gnu/release/"$project_name" artifacts/"$project_name"-linux
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifactes
